name: Go build

on:
  workflow_call:
      inputs:
        suiteName:
          description: 'Suite name'
          default: 'check-basic'
          required: false
          type: string
        binary:
          required: false
          type: string
      secrets:
        token:
          required: false

env:
  GO_VERSION: ^1.16
  GO_VERSION_WIN: ^1.13

jobs:
  smoketest:
    name: Smoke test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Reference and Set Cache Name
        run: |
          PR_NUMBER=$(echo ${GITHUB_REF} | cut -d / -f 3 )
          echo "cachePrefix=k0s-${PR_NUMBER}-${{ github.sha }}" >> $GITHUB_ENV
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - uses: actions/download-artifact@v2
        with:
          name: k0s-${{env.cachePrefix}}
          path: k0s

      - name: Run test .
        run: make -C inttest check-basic

      - name: Collect test logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: |
            /tmp/*.log